### ISSUE TITLE
World generation crash

### ISSUE THREAD

**Issue by sscards55** [RootsTeam/Embers#110]
Setting both the min and max Y level to 0 for any ore causes a server-side crash.

[02:40:19] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_121]
	at teamroots.embers.world.WorldGenOres.generate(WorldGenOres.java:31) ~[WorldGenOres.class:?]
	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120) ~[GameRegistry.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001) ~[asv.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983) ~[asv.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) ~[lr.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:106) ~[bzl.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:120) ~[bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]

**Comment by elucent** [comment]
Why would you set both the min and max Y to zero? If you're trying to disable ore generation, you should set the number of veins to zero, or set the chance of a vein per chunk to zero. This isn't really my fault -- my config just sends the values directly to a vanilla ore generation class. You're giving it broken values.

**Comment by sscards55** [comment]
1. Yes, I was trying to disable ore generation.
2. I didn't know that.(You might want to add that to the configuration comment.)
3. Not entirely your fault Random doesn't know how to deal with 0 bound arguments.

Sometimes when someone doesn't know how something works and tries to change it, they end up breaking it. That's why you should instruct them. I didn't know how your oregen worked so I ended up breaking it.

**Comment by elucent** [comment]
It's no big deal, just not an issue. Sorry if I was a little terse, sometimes people can get a little heated about this.

**Comment by sscards55** [comment]
That's fine. Sadly most people aren't as understanding as I am.
