### ISSUE TITLE
RecipeSorter

### ISSUE THREAD

**Issue by bookerthegeek** [RootsTeam/Embers#204]
## Heyo ##
Saw this in the log, thought I would through it your way. 
```
[13:27:12] [Client thread/WARN] [FML]: ****************************************
[13:27:12] [Client thread/WARN] [FML]: * Unknown recipe class! teamroots.embers.recipe.AshenCloakSocketRecipe Modders need to register their recipe types with net.minecraftforge.oredict.RecipeSorter
[13:27:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.getPriority(RecipeSorter.java:241)
[13:27:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:176)
[13:27:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:55)
[13:27:12] [Client thread/WARN] [FML]: *  at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
[13:27:12] [Client thread/WARN] [FML]: *  at java.util.TimSort.sort(Unknown Source)
[13:27:12] [Client thread/WARN] [FML]: *  at java.util.Arrays.sort(Unknown Source)...
[13:27:12] [Client thread/WARN] [FML]: ****************************************
[13:27:12] [Client thread/WARN] [FML]: ****************************************
[13:27:12] [Client thread/WARN] [FML]: * Unknown recipe class! teamroots.embers.recipe.AshenCloakUnsocketRecipe Modders need to register their recipe types with net.minecraftforge.oredict.RecipeSorter
[13:27:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.getPriority(RecipeSorter.java:241)
[13:27:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:176)
[13:27:12] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.RecipeSorter.compare(RecipeSorter.java:55)
[13:27:12] [Client thread/WARN] [FML]: *  at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
[13:27:12] [Client thread/WARN] [FML]: *  at java.util.TimSort.sort(Unknown Source)
[13:27:12] [Client thread/WARN] [FML]: *  at java.util.Arrays.sort(Unknown Source)...
[13:27:12] [Client thread/WARN] [FML]: ****************************************
```
##
### Versions ###
- Minecraft 1.11.2
- embers-0.214

**Comment by elucent** [comment]
Added.
