### ISSUE TITLE
BlockPos cast issue with Hwyla/Waila

### ISSUE THREAD

**Issue by darkhax** [RootsTeam/Embers#229]
There is sometimes a weird BlockPos cast issue when looking at a fairy thing with Hwyla/Waila and Wawla installed. 0.219

[full log](https://pastebin.com/CzXT0Akw)

```
java.lang.ClassCastException: net.minecraft.util.math.BlockPos cannot be cast to java.lang.Integer
    at teamroots.roots.entity.EntityFairy.getRed(EntityFairy.java:100)
    at teamroots.roots.entity.EntityFairy.func_70071_h_(EntityFairy.java:149)
    at net.minecraft.world.World.func_72866_a(World.java:1976)
    at net.minecraft.world.World.func_72870_g(World.java:1939)
    at net.minecraft.world.World.func_72939_s(World.java:1753)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1841)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by elucent** [comment]
This is a Roots bug, not an Embers bug. And this is likely not my fault, somebody else is likely screwing with the DataWatcher: https://github.com/Vazkii/Botania/issues/2114#issuecomment-272708867

**Comment by darkhax** [comment]
Whoops, sorry! I got confused. Thanks for the info on this issue.
