### ISSUE TITLE
Ore dictionary warnings in 1.12 log

### ISSUE THREAD

**Issue by PrinceOfAmber** [RootsTeam/Embers#234]
fml client latest log

 embers-0.219.jar

[08:11:14] [main/TRACE] [FML/embers]: Automatically registered mod embers entity ember_light as embers:ember_light
[08:11:14] [main/WARN] [FML/embers]: ****************************************
[08:11:14] [main/WARN] [FML/embers]: * A broken ore dictionary registration with name nuggetIron has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[08:11:14] [main/WARN] [FML/embers]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[08:11:14] [main/WARN] [FML/embers]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[08:11:14] [main/WARN] [FML/embers]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[08:11:14] [main/WARN] [FML/embers]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:512)
[08:11:14] [main/WARN] [FML/embers]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[08:11:14] [main/WARN] [FML/embers]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[08:11:14] [main/WARN] [FML/embers]: ****************************************
[08:11:14] [main/WARN] [FML/embers]: ****************************************
[08:11:14] [main/WARN] [FML/embers]: * A broken ore dictionary registration with name dustAsh has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[08:11:14] [main/WARN] [FML/embers]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[08:11:14] [main/WARN] [FML/embers]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[08:11:14] [main/WARN] [FML/embers]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[08:11:14] [main/WARN] [FML/embers]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:513)
[08:11:14] [main/WARN] [FML/embers]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[08:11:14] [main/WARN] [FML/embers]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[08:11:14] [main/WARN] [FML/embers]: ****************************************
[08:11:14] [main/WARN] [FML/embers]: ****************************************
[08:11:14] [main/WARN] [FML/embers]: * A broken ore dictionary registration with name dustAshes has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[08:11:14] [main/WARN] [FML/embers]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[08:11:14] [main/WARN] [FML/embers]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[08:11:14] [main/WARN] [FML/embers]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[08:11:14] [main/WARN] [FML/embers]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:514)
[08:11:14] [main/WARN] [FML/embers]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[08:11:14] [main/WARN] [FML/embers]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[08:11:14] [main/WARN] [FML/embers]: ****************************************

**Comment by elucent** [comment]
IIRC this was fixed in 0.220, let me know if it wasn't.

**Comment by the-ible** [comment]
I confirm this issue is reproduced on Minecraft 1.12 using embers version 0.221

[23:06:22] [main/WARN]: ****************************************
[23:06:22] [main/WARN]: * A broken ore dictionary registration with name nuggetIron has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[23:06:22] [main/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[23:06:22] [main/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[23:06:22] [main/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[23:06:22] [main/WARN]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:512)
[23:06:22] [main/WARN]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[23:06:22] [main/WARN]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[23:06:22] [main/WARN]: ****************************************
[23:06:22] [main/WARN]: ****************************************
[23:06:22] [main/WARN]: * A broken ore dictionary registration with name dustAsh has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[23:06:22] [main/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[23:06:22] [main/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[23:06:22] [main/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[23:06:22] [main/WARN]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:513)
[23:06:22] [main/WARN]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[23:06:22] [main/WARN]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[23:06:22] [main/WARN]: ****************************************
[23:06:22] [main/WARN]: ****************************************
[23:06:22] [main/WARN]: * A broken ore dictionary registration with name dustAshes has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Embers report it to them!
[23:06:22] [main/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
[23:06:22] [main/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
[23:06:22] [main/WARN]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
[23:06:22] [main/WARN]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:514)
[23:06:22] [main/WARN]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
[23:06:22] [main/WARN]: *  at teamroots.embers.proxy.ClientProxy.preInit(ClientProxy.java:17)...
[23:06:22] [main/WARN]: ****************************************

**Comment by elucent** [comment]
Should be fixed in 0.230.
