### ISSUE TITLE
Please Register items to ore dictionary after Game Registry

### ISSUE THREAD

**Issue by tyler489** [RootsTeam/Embers#241]
Using the newest version of embers for 1.12
not a huge issue but i have like 10 mods doing this and the spam is insane...
```28.07 02:49:32 [Server] Server thread/WARN [FML]: ****************************************
28.07 02:49:32 [Server] Server thread/WARN [FML]: * A broken ore dictionary registration with name nuggetIron has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
28.07 02:49:32 [Server] INFO TO USERS: YES this is a BUG in the mod Embers report it to them!
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:512)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at teamroots.embers.proxy.ServerProxy.preInit(ServerProxy.java:10)...
28.07 02:49:32 [Server] Server thread/WARN [FML]: ****************************************
28.07 02:49:32 [Server] Server thread/WARN [FML]: ****************************************
28.07 02:49:32 [Server] Server thread/WARN [FML]: * A broken ore dictionary registration with name dustAsh has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
28.07 02:49:32 [Server] INFO TO USERS: YES this is a BUG in the mod Embers report it to them!
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:513)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at teamroots.embers.proxy.ServerProxy.preInit(ServerProxy.java:10)...
28.07 02:49:32 [Server] Server thread/WARN [FML]: ****************************************
28.07 02:49:32 [Server] Server thread/WARN [FML]: ****************************************
28.07 02:49:32 [Server] Server thread/WARN [FML]: * A broken ore dictionary registration with name dustAshes has occurred. It adds an item (type: class teamroots.embers.item.ItemBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
28.07 02:49:32 [Server] INFO TO USERS: YES this is a BUG in the mod Embers report it to them!
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:633)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:605)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:603)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at teamroots.embers.RegistryManager.registerAll(RegistryManager.java:514)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at teamroots.embers.proxy.CommonProxy.preInit(CommonProxy.java:22)
28.07 02:49:32 [Server] Server thread/WARN [FML]: *  at teamroots.embers.proxy.ServerProxy.preInit(ServerProxy.java:10)...
28.07 02:49:32 [Server] Server thread/WARN [FML]: ****************************************```

**Comment by tyler489** [comment]
sorry just found #234
