### ISSUE TITLE
Crashes with some Embers machines and pipes

### ISSUE THREAD

**Issue by Reoseah** [RootsTeam/Embers#25]
Experimenting with different Embers machines, I have crashes randomly occuring... Setup like this usually makes crash on my PC in less then 3-5 minutes, sometimes just instantly:
![2016-10-20_15 51 32](https://cloud.githubusercontent.com/assets/20323084/19561277/b1c46ad8-96e0-11e6-8566-19eead674df5.png)
With stacktrace like this:
```
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.world.World.updateEntities(World.java:1957) ~[World.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1886) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1118) ~[Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:406) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [start/:?]
	at GradleStart.main(GradleStart.java:26) [start/:?]
Caused by: java.lang.NullPointerException
	at teamroots.embers.tileentity.TileEntityItemPipe.update(TileEntityItemPipe.java:209) ~[TileEntityItemPipe.class:?]
	at net.minecraft.world.World.updateEntities(World.java:1942) ~[World.class:?]
	... 16 more
```
Other place where crashes often occur is TileEntityBinRenderer.

In all places NPE is thrown just after checking for item in bin inventory being not null...
The reason is modifying inventory from network-thread. Reason seems to be in MessageTEUpdate.MessageHolder.onMessage(...).
Correct code should use Minecraft.getMinecraft().addSheduledTask(Runnable r) instead of running code directly.
So this should fix issue:
``` java
public IMessage onMessage(final MessageTEUpdate message, final MessageContext ctx) {
	Minecraft.getMinecraft().addScheduledTask(() -> {
		if ((Minecraft.getMinecraft().thePlayer.getEntityWorld())
				.getTileEntity(new BlockPos(message.tag.getInteger("x"), message.tag.getInteger("y"),
						message.tag.getInteger("z"))) != null) {
			Minecraft.getMinecraft().thePlayer.getEntityWorld()
					.getTileEntity(new BlockPos(message.tag.getInteger("x"), message.tag.getInteger("y"),
							message.tag.getInteger("z"))).readFromNBT(message.tag);
		}
	});
	return null;
}
```
It haven't crashed after this change for me.

**Comment by elucent** [comment]
Fixed this, thank you for all your help!

**Comment by Reoseah** [comment]
Stacktrace also shows another problem. It don't cause any visible issues, but it consumes system resources and, perhaps, may lead to FPS decrease: the code in TileEntityItemPipe.update() seems to be not needed at client at all.

So something like this can be added at beginning of this method:
``` java
if (worldObj.isRemote)
	return;
```

Perhaps it applies to other tiles in mod, but I haven't time to see them all.
