### ISSUE TITLE
Ticking entity crash 1.12

### ISSUE THREAD

**Issue by X1machinemaker1X** [RootsTeam/Embers#263]
5 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.insertItem(ServoItem.java:390)
	at cofh.thermaldynamics.duct.attachments.servo.ServoItem.insertItem(ServoItem.java:459)
	at teamroots.embers.tileentity.TileEntityItemVacuum.func_73660_a(TileEntityItemVacuum.java:190)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

[crash-2017-11-10_16.45.23-client.txt](https://github.com/RootsTeam/Embers/files/1463068/crash-2017-11-10_16.45.23-client.txt)
[crash-2017-11-10_16.39.33-client.txt](https://github.com/RootsTeam/Embers/files/1463069/crash-2017-11-10_16.39.33-client.txt)

**Comment by annihone** [comment]
This is most likely a Thermal Dynamics issue. You should report this to [https://github.com/CoFH/ThermalDynamics](url).

**Comment by melbellrocks** [comment]
I just had this as well so I hit the google to figure out if there's a way to fix it.  I found this first, so I went over to the Thermal Dynamics github and on Sep 5th someone over there said it's an embers problem.

"Looked over the code. This is on Embers' end - they are not correctly isolating their client and server code and are trying to do item transfer on the client, which is incorrect."

https://github.com/CoFH/Feedback/issues/526
