### ISSUE TITLE
Crash with Refined Relocation

### ISSUE THREAD

**Issue by RoyAwesome** [RootsTeam/Embers#39]
Hey dudes, your mod is crashing with Refined Relocation

Place a Embers Copper Cell, then look at it and press sneak, and you get a crash.  

```
Description: Unexpected error

java.lang.ClassCastException: teamroots.embers.power.DefaultEmberCapability cannot be cast to net.blay09.mods.refinedrelocation.api.grid.ISortingGridMember
at net.blay09.mods.refinedrelocation.client.BlockHighlightHandler.onBlockHighlight(BlockHighlightHandler.java:25)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_831_BlockHighlightHandler_onBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at Reflector.callBoolean(Reflector.java:352)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1748)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1557)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1336)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

[crash-2016-11-20_02.58.59-client.txt](https://github.com/RootsTeam/Embers/files/602381/crash-2016-11-20_02.58.59-client.txt)

Refined Relocation says it's your fault: https://github.com/Dynious/RefinedRelocation/issues/404

Here is the relevant issue report w/ All The Mods: https://github.com/whatthedrunk/allthemods/issues/290

**Comment by elucent** [comment]
I fixed a lot of these issues a while ago, must have missed one. It's fixed now!

**Comment by eyekantspel** [comment]
Looks like it may still be happening, running version 0.016;

```
Description: Unexpected error

java.lang.ClassCastException: teamroots.embers.power.DefaultEmberCapability cannot be cast to net.blay09.mods.refinedrelocation.api.grid.ISortingGridMember
	at net.blay09.mods.refinedrelocation.client.BlockHighlightHandler.onBlockHighlight(BlockHighlightHandler.java:25)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_822_BlockHighlightHandler_onBlockHighlight_DrawBlockHighlightEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.onDrawBlockHighlight(ForgeHooksClient.java:161)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1329)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

[crash-2016-11-29_19.06.17-client.txt](https://github.com/RootsTeam/Embers/files/620608/crash-2016-11-29_19.06.17-client.txt)

**Comment by elucent** [comment]
Yeah, I haven't yet released a version with a fix. I have too many incomplete features at the moment, but I'll try and get something out fairly soon.
