### ISSUE TITLE
Crash on world startup after client crash

### ISSUE THREAD

**Issue by sscards55** [RootsTeam/Embers#41]
Time: 11/22/16 1:52 PM
Description: Exception while updating neighbours

java.lang.ClassCastException: crazypants.enderio.conduit.TileConduitBundle cannot be cast to teamroots.embers.tileentity.TileEntityEmitter
	at teamroots.embers.block.BlockEmberEmitter.func_189540_a(BlockEmberEmitter.java:80)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_189546_a(BlockStateContainer.java:463)
	at net.minecraft.world.World.func_180496_d(World.java:519)
	at net.minecraft.world.World.func_175685_c(World.java:469)
	at crazypants.enderio.conduit.TileConduitBundle.doConduitsDirty(TileConduitBundle.java:260)
	at crazypants.enderio.conduit.TileConduitBundle.doUpdate(TileConduitBundle.java:243)
	at com.enderio.core.common.TileEntityBase.func_73660_a(TileEntityBase.java:36)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:619)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

Seems like you're not checking types

**Comment by elucent** [comment]
I wasn't checking types, but that shouldn't be necessary either. How would BlockEmberEmitter#neighborChanged fire for a non-BlockEmberEmitter block, is my question.

Regardless, I've added an additional check that should prevent this from happening again.
