### ISSUE TITLE
Crash when placing Ember Receiver on crossroads' fluid cooling chamber

### ISSUE THREAD

**Issue by luckdemon** [RootsTeam/Embers#42]
Accidentally placed an ember receiver on the side of a Crossroads' fluid cooling chamber, this crash ensued. Crashed every client connected to the server, the server, and repeatedly crashed the server on startup.

Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at teamroots.embers.tileentity.TileEntityReceiver.func_73660_a(TileEntityReceiver.java:94)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by elucent** [comment]
Tell the Crossroads dev to implement hasCapability properly. The only way this could happen is if a value of "true" was returned for a check to see if the tile entity has an ember capability.
